import { chromium, devices } from "playwright-core";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const ctx = await b.newContext({ ...devices["Pixel 7"] }); const page = await ctx.newPage();
await page.addInitScript(() => localStorage.setItem("pintorpro:no-tours", "1"));
await page.goto("http://localhost:3000/onboarding"); await page.waitForTimeout(3500);
await page.evaluate(()=>{localStorage.setItem("pintorpro:v1", JSON.stringify({version:1,company:{name:"S",whatsapp:"1",city:"SP",paymentTerms:"x",hoursPerDay:8,marginPct:30,dailyRateCents:25000,safetyDays:1,pricingMode:"base_price"},services:[],materials:[],enabledServiceIds:[],quotes:[],works:[],clients:[],visits:[],counters:{quote:0}}))});
await page.goto("http://localhost:3000/visitas"); await page.waitForTimeout(3000);
await page.getByRole("button", { name: /nova visita/i }).click();
await page.getByRole("button", { name: "Começar agora" }).click();
await page.getByText("Nenhuma foto", { exact: true }).waitFor();
await page.getByTestId("photo-input").setInputFiles("tests/foto-teste.png");
await page.getByText("1 foto", { exact: true }).waitFor();
await page.waitForTimeout(1000);
console.log(await page.getByRole("button",{name:/^Fotos/}).getAttribute("aria-expanded"));
await page.screenshot({path:"/tmp/dbg.png"});
