// Primeiro uso: 2 perguntas, ida às Visitas e confirmação de preço no próprio orçamento.
import { chromium, devices } from "playwright-core";
const base = process.env.BASE ?? "http://localhost:3000";
const exe = process.env.CHROME ?? "/opt/pw-browsers/chromium-1194/chrome-linux/chrome";
const browser = await chromium.launch({ executablePath: exe });
const ctx = await browser.newContext({ ...devices["Pixel 7"] });
const page = await ctx.newPage();
await page.addInitScript(() => localStorage.setItem("pintorpro:no-tours", "1"));
const errors = [];
page.on("pageerror", (e) => errors.push(e.message));
const fails = [];
const check = (ok, msg) => { console.log(ok ? "OK  " : "FALHOU", msg); if (!ok) fails.push(msg); };
const next = () => page.getByRole("button", { name: /Continuar|Começar/ }).click();
await page.goto(base);
await page.waitForURL("**/onboarding");
await page.getByPlaceholder("Ex.: João Pinturas").fill("Silva Pinturas"); await next();
await page.getByPlaceholder("(11) 99999-9999").fill("11988887777"); await next();
await page.waitForURL(base + "/visitas");
check(page.url().endsWith("/visitas"), "depois de 2 perguntas o pintor cai na tela de Visitas");
await page.goto(base + "/orcamentos/novo");
check(!(await page.getByText("Confirme seus preços").isVisible().catch(() => false)), "sem medidas, ainda não pede preço");
await page.getByLabel("Parede 1 largura").fill("12");
await page.getByText("Confirme seus preços").waitFor();
check(!(await page.getByLabel(/Preço de /).first().isVisible()), "os preços individuais começam recolhidos (a tela não fica enorme)");
await page.getByText("Ajustar um por um").click();
const price = page.getByLabel(/Preço de /).first();
const before = await page.getByTestId("total").innerText();
await price.fill("30");
await page.getByRole("button", { name: "Usar este preço" }).first().click();
await page.waitForTimeout(400);
check((await page.getByTestId("total").innerText()) !== before, "o preço confirmado muda o total na hora");
check((await page.getByLabel(/Preço de /).count()) === 0 || (await page.getByLabel(/Preço de /).first().inputValue()) !== "30", "serviço confirmado sai da lista");
const cfg = await page.evaluate(() => JSON.parse(localStorage.getItem("pintorpro:v1")).company);
check(cfg.name === "Silva Pinturas" && cfg.whatsapp === "11988887777", "dados das 2 perguntas guardados");
console.log(errors.length ? "ERROS DE CONSOLE: " + errors.join("; ") : "erros de console: nenhum");
await browser.close();
if (fails.length) { console.log("\n" + fails.length + " falha(s)"); process.exit(1); }
console.log("\nTudo certo.");
